jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token:${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_FIELD_04A0F6D0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"         # <-- THIS is what was missing

          app_location: "/"        # index.html is in the repo root
          output_location: "/"     # serve from root
          api_location: ""         # no API

          skip_app_build: true     # don't run Oryx / npm
          skip_api_build: true
